# A lower number will lead to a higher chance of dropping.
[drop_chances]
    # If set to 1 or below, the value will be overriden and set to 2.
    special = 100
    night = 5700
    day = 17000

# Weight: (Basically) How often the pigeons will spawn. Max Group: The upper limit for how many pigeons
# will spawn in a group. Min Group: The lower limit for how many pigeons will spawn in a group.
[spawning]
    # No biomes are in here, by default.
    [spawning.high]
        weight = 65
        max_group = 9
        min_group = 3
    # Jungle and Savanna are include,d by default.
    [spawning.low]
        weight = 15
        max_group = 2
        min_group = 1
    # Plains and Forest (oak) are included, by default.
    [spawning.medium]
        weight = 45
        max_group = 6
        min_group = 2

[special_drops]

    [special_drops.city]
        item = "minecraft:diamond"
        count = 1

    [special_drops.egyptian]
        item = "minecraft:cooked_beef"
        count = 5

    [special_drops.antwerp_gray]
        item = "minecraft:raw_copper"
        count = 7

    [special_drops.antwerp_brown]
        item = "minecraft:raw_iron"
        count = 3

[common_drops]
    drops = [
        "minecraft:wheat_seeds",
        "minecraft:beetroot_seeds",
        "minecraaft:melon_seeds",
        "minecraft:pumpkin_seeds",
        "minecraft:raw_iron",
        "minecraft:dirt"
    ]