[special_drops]
    [special_drops.city]
        item = "minecraft:diamond"
        count = 1
    [special_drops.antwerp_brown]
        item = "minecraft:raw_iron"
        count = 3
    [special_drops.antwerp_gray]
        item = "minecraft:raw_copper"
        count = 7
    [special_drops.egyptian]
        item = "minecraft:cooked_beef"
        count = 5

[drop_chances] # A lower number will lead to a higher chance of dropping.
    day = 17000
    night = 5700
    special = 100 # If set to 1 or below, the value will be overriden and set to 2.