# A lower number will lead to a higher chance of dropping.
[drop_chances]
    # If set to 1 or below, the value will be overriden and set to 2.
    special = 100
    night = 5700
    day = 17000

[spawning]

    [spawning.high]
        weight = 65
        max_group = 9
        min_group = 3

    [spawning.low]
        weight = 15
        max_group = 2
        min_group = 1

    [spawning.medium]
        weight = 45
        max_group = 6
        min_group = 2

[special_drops]

    [special_drops.city]
        item = "minecraft:diamond"
        count = 1

    [special_drops.egyptian]
        item = "minecraft:cooked_beef"
        count = 5

    [special_drops.antwerp_gray]
        item = "minecraft:raw_copper"
        count = 7

    [special_drops.antwerp_brown]
        item = "minecraft:raw_iron"
        count = 3

[common_drops]
    drops = [
        "minecraft:wheat_seeds",
        "minecraft:beetroot_seeds",
        "minecraaft:melon_seeds",
        "minecraft:pumpkin_seeds",
        "minecraft:raw_iron",
        "minecraft:dirt"
    ]